import { AppDispatch, RootState } from './store';
import { ScoreTracker, pushScore } from './store/slices/StatSlice';

////////////////////////////////////////////////////////////////////////////////////
function CalculateWPM(
  useCountdown: boolean,
  timeElapsed: number,
  countdownTimer: number,
  startingTime: number,
  excessQuoteToType: string,
  quoteToType: string,
  duplicateQuoteToType: string,
  userTextInput: string
): number {
  const correct = calculateCorrectCharacters(
    excessQuoteToType,
    quoteToType,
    duplicateQuoteToType,
    userTextInput
  );

  if (useCountdown) {
    const dupWpm =
      +(correct / 5 / ((startingTime - countdownTimer) / 60)).toFixed(2) || 0;
    return dupWpm;
  } else {
    const dupWpm = +(correct / 5 / (timeElapsed / 60)).toFixed(2);
    return dupWpm;
  }
}
////////////////////////////////////////////////////////////////////////////////////

function calculateCorrectCharacters(
  excessQuoteToType: string,
  quoteToType: string,
  duplicateQuoteToType: string,
  userTextInput: string
): number {
  const logicData = deleteExcessLettersData(
    userTextInput,
    duplicateQuoteToType,
    quoteToType
  );

  const numOfIncorrectCharsInWord = incorrectCharsInCurrentWord(
    logicData.reassignWord,
    logicData.currentWordNumber - 1,
    excessQuoteToType
  );

  const allLettersTyped = excessQuoteToType.length;
  const timesSkipped = excessQuoteToType?.match(/[#]/g)?.length;
  const lettersInMispelledWords = excessQuoteToType
    .split(' ')
    .filter(
      (word, idx) =>
        word !== duplicateQuoteToType.split(' ')[idx] &&
        idx !== logicData.currentWordNumber - 1
    )
    .join('').length;

  return (
    allLettersTyped -
    (timesSkipped || 0) -
    lettersInMispelledWords -
    numOfIncorrectCharsInWord
  );
}

////////////////////////////////////////////////////////////////////////////////////
function calculateAccuracy(
  totalKeysPressed: number,
  incorrectKeys: number,
  userTextInput: string
): number {
  const incorrectNonSkipped =
    // Regex finds '%' char which represents letters that were skipped by pressing space early on a word, which shouldn't count towards incorrect letters
    incorrectKeys - userTextInput.replace(/[^%]/g, '').length;
  return +((totalKeysPressed - incorrectNonSkipped) / totalKeysPressed).toFixed(
    2
  );
}

////////////////////////////////////////////////////////////////////////////////////
function calculateRaw(totalKeysPressed: number, time: number): number {
  const raw = +(totalKeysPressed / 5 / (time / 60)).toFixed(2);
  return raw;
}

////////////////////////////////////////////////////////////////////////////////////

function incorrectKeyPresses(
  excessQuoteToType: string,
  incorrectKeys: number
): number {
  const skippedChars = excessQuoteToType?.match(/[%]/g)?.length;
  return skippedChars ? incorrectKeys - skippedChars : incorrectKeys;
}

////////////////////////////////////////////////////////////////////////////////////

function incorrectCharsInCurrentWord(
  reassignWord: string,
  currentWordNumber: number,
  excessQuoteToType: string
): number {
  let incorrectChars = 0;
  const userTypedWord = excessQuoteToType.split(' ')[currentWordNumber];
  let userTypedChar;
  for (let idx = 0; idx < userTypedWord.length; idx++) {
    if (excessQuoteToType) {
      userTypedChar = excessQuoteToType.split(' ')[currentWordNumber][idx];
    }
    const correctChar = reassignWord[idx];
    if (userTypedChar !== correctChar) incorrectChars++;
  }
  return incorrectChars;
}
////////////////////////////////////////////////////////////////////////////////////
function addScoreToState(
  currentScores: ScoreTracker[],
  dispatch: AppDispatch,
  wpm: number,
  raw: number,
  errors: number,
  time: number,
  func: typeof pushScore
): void {
  const recentErrors = currentScores.reduce((acc, cv) => acc + cv.errors, 0);

  dispatch(
    func({
      raw,
      wpm,
      errors: errors - recentErrors,
      time,
    })
  );
}
////////////////////////////////////////////////////////////////////////////////////

function focusTextArea(): void {
  const testTextArea = document.getElementById('type-test');
  testTextArea?.focus();
}

////////////////////////////////////////////////////////////////////////////////////
export interface KeyLogic {
  currentWordNumber: number;
  userInputWordLength: number;
  quoteWordLength: number;
  quoteWord: string;
  userTypedWord: string;
  reassignWord: string;
  splitQuote: string[];
  lettersRemainingInCurrentWord: number;
}

function deleteExcessLettersData(
  userTextInput: string,
  duplicateQuoteToType: string,
  quoteToType: string
): KeyLogic {
  const currentWordNumber = userTextInput.split(' ').length;

  const userInputWordLength =
    userTextInput.split(' ')[currentWordNumber - 1].length;

  const quoteWordLength =
    duplicateQuoteToType.split(' ')[currentWordNumber - 1].length;

  const quoteWord = duplicateQuoteToType.split(' ')[currentWordNumber - 1];

  const userTypedWord = userTextInput
    .split(' ')
    [currentWordNumber - 1].slice(
      0,
      userTextInput.split(' ')[currentWordNumber - 1].length - 1
    );

  const reassignWord = quoteWord.concat(
    userTypedWord.slice(quoteWordLength, userInputWordLength - 1)
  );

  const splitQuote = quoteToType.split(' ');

  const lettersRemainingInCurrentWord = quoteWordLength - userInputWordLength;

  return {
    currentWordNumber,
    userInputWordLength,
    quoteWordLength,
    quoteWord,
    userTypedWord,
    reassignWord,
    splitQuote,
    lettersRemainingInCurrentWord,
  };
}

////////////////////////////////////////////////////////////////////////////////////
function remakeQuoteString(
  userTextInput: string,
  duplicateQuoteToType: string,
  quoteToType: string
): string {
  const logicData = deleteExcessLettersData(
    userTextInput,
    duplicateQuoteToType,
    quoteToType
  );
  const splitQuote = logicData.splitQuote;
  // Replacing the current word with what was deleted from user input
  splitQuote[logicData.currentWordNumber - 1] = logicData.reassignWord;
  return splitQuote.join(' ');
}
////////////////////////////////////////////////////////////////////////////////////

function generateTest(state: RootState): string[] {
  let wordsToGenerate;
  if (state.statSlice.useCountdown) {
    wordsToGenerate = 100;
  } else {
    wordsToGenerate = state.typeInput.numOfWordsToType;
  }
  const randomWordList = [];

  for (let i = 0; i < wordsToGenerate; i++) {
    if (state.statSlice.language === 'HTML') {
      const randomNumber = Math.floor(Math.random() * 100);
      if (randomNumber > 50) {
        randomWordList.push(
          `</${
            htmlElementsList[
              Math.floor(Math.random() * htmlElementsList.length)
            ]
          }>`
        );
      } else {
        randomWordList.push(
          `<${
            htmlElementsList[
              Math.floor(Math.random() * htmlElementsList.length)
            ]
          }>`
        );
      }
    } else if (state.statSlice.language === 'JavaScript') {
      randomWordList.push(
        javascriptWordList[
          Math.floor(Math.random() * javascriptWordList.length)
        ]
      );
    } else {
      randomWordList.push(
        state.typeInput.wordList[
          Math.floor(Math.random() * state.typeInput.wordList.length)
        ]
      );
    }
  }
  return randomWordList;
}

////////////////////////////////////////////////////////////////////////////////////
export {
  deleteExcessLettersData,
  remakeQuoteString,
  CalculateWPM,
  calculateAccuracy,
  focusTextArea,
  generateTest,
  calculateRaw,
  incorrectKeyPresses,
  addScoreToState,
};

export const allWordsList = [
  'a',
  'ability',
  'able',
  'about',
  'above',
  'accept',
  'according',
  'account',
  'across',
  'act',
  'action',
  'activity',
  'actually',
  'add',
  'address',
  'administration',
  'admit',
  'adult',
  'affect',
  'after',
  'again',
  'against',
  'age',
  'agency',
  'agent',
  'ago',
  'agree',
  'agreement',
  'ahead',
  'air',
  'all',
  'allow',
  'almost',
  'alone',
  'along',
  'already',
  'also',
  'although',
  'always',
  'among',
  'amount',
  'analysis',
  'and',
  'animal',
  'another',
  'answer',
  'any',
  'anyone',
  'anything',
  'appear',
  'apply',
  'approach',
  'area',
  'argue',
  'arm',
  'around',
  'arrive',
  'art',
  'article',
  'artist',
  'as',
  'ask',
  'assume',
  'at',
  'attack',
  'attention',
  'attorney',
  'audience',
  'author',
  'authority',
  'available',
  'avoid',
  'away',
  'baby',
  'back',
  'bad',
  'bag',
  'ball',
  'bank',
  'bar',
  'base',
  'be',
  'beat',
  'beautiful',
  'because',
  'become',
  'bed',
  'before',
  'begin',
  'behavior',
  'behind',
  'believe',
  'benefit',
  'best',
  'better',
  'between',
  'beyond',
  'big',
  'bill',
  'billion',
  'bit',
  'black',
  'blood',
  'blue',
  'board',
  'body',
  'book',
  'born',
  'both',
  'box',
  'boy',
  'break',
  'bring',
  'brother',
  'budget',
  'build',
  'building',
  'business',
  'but',
  'buy',
  'by',
  'call',
  'camera',
  'campaign',
  'can',
  'cancer',
  'candidate',
  'capital',
  'car',
  'card',
  'care',
  'career',
  'carry',
  'case',
  'catch',
  'cause',
  'cell',
  'center',
  'central',
  'century',
  'certain',
  'certainly',
  'chair',
  'challenge',
  'chance',
  'change',
  'character',
  'charge',
  'check',
  'child',
  'choice',
  'choose',
  'church',
  'citizen',
  'city',
  'civil',
  'claim',
  'class',
  'clear',
  'clearly',
  'close',
  'coach',
  'cold',
  'collection',
  'college',
  'color',
  'come',
  'commercial',
  'common',
  'community',
  'company',
  'compare',
  'computer',
  'concern',
  'condition',
  'conference',
  'consider',
  'consumer',
  'contain',
  'continue',
  'control',
  'cost',
  'could',
  'country',
  'couple',
  'course',
  'court',
  'cover',
  'create',
  'crime',
  'cultural',
  'culture',
  'cup',
  'current',
  'customer',
  'cut',
  'dark',
  'data',
  'daughter',
  'day',
  'dead',
  'deal',
  'death',
  'debate',
  'decade',
  'decide',
  'decision',
  'deep',
  'defense',
  'degree',
  'democratic',
  'describe',
  'design',
  'despite',
  'detail',
  'determine',
  'develop',
  'development',
  'die',
  'difference',
  'different',
  'difficult',
  'dinner',
  'direction',
  'director',
  'discover',
  'discuss',
  'discussion',
  'disease',
  'do',
  'doctor',
  'dog',
  'door',
  'down',
  'draw',
  'dream',
  'drive',
  'drop',
  'drug',
  'during',
  'each',
  'early',
  'east',
  'easy',
  'eat',
  'economic',
  'economy',
  'edge',
  'education',
  'effect',
  'effort',
  'eight',
  'either',
  'election',
  'else',
  'employee',
  'end',
  'energy',
  'enjoy',
  'enough',
  'enter',
  'entire',
  'environment',
  'environmental',
  'especially',
  'establish',
  'even',
  'evening',
  'event',
  'ever',
  'every',
  'everybody',
  'everyone',
  'everything',
  'evidence',
  'exactly',
  'example',
  'executive',
  'exist',
  'expect',
  'experience',
  'expert',
  'explain',
  'eye',
  'face',
  'fact',
  'factor',
  'fail',
  'fall',
  'family',
  'far',
  'fast',
  'father',
  'fear',
  'federal',
  'feel',
  'feeling',
  'few',
  'field',
  'fight',
  'figure',
  'fill',
  'film',
  'final',
  'finally',
  'financial',
  'find',
  'fine',
  'finger',
  'finish',
  'fire',
  'firm',
  'first',
  'fish',
  'five',
  'floor',
  'fly',
  'focus',
  'follow',
  'food',
  'foot',
  'for',
  'force',
  'foreign',
  'forget',
  'form',
  'former',
  'forward',
  'four',
  'free',
  'friend',
  'from',
  'front',
  'full',
  'fund',
  'future',
  'game',
  'garden',
  'gas',
  'general',
  'generation',
  'get',
  'girl',
  'give',
  'glass',
  'go',
  'goal',
  'good',
  'government',
  'great',
  'green',
  'ground',
  'group',
  'grow',
  'growth',
  'guess',
  'gun',
  'guy',
  'hair',
  'half',
  'hand',
  'hang',
  'happen',
  'happy',
  'hard',
  'have',
  'he',
  'head',
  'health',
  'hear',
  'heart',
  'heat',
  'heavy',
  'help',
  'her',
  'here',
  'herself',
  'high',
  'him',
  'himself',
  'his',
  'history',
  'hit',
  'hold',
  'home',
  'hope',
  'hospital',
  'hot',
  'hotel',
  'hour',
  'house',
  'how',
  'however',
  'huge',
  'human',
  'hundred',
  'husband',
  'idea',
  'identify',
  'if',
  'image',
  'imagine',
  'impact',
  'important',
  'improve',
  'in',
  'include',
  'including',
  'increase',
  'indeed',
  'indicate',
  'individual',
  'industry',
  'information',
  'inside',
  'instead',
  'institution',
  'interest',
  'interesting',
  'international',
  'interview',
  'into',
  'investment',
  'involve',
  'issue',
  'it',
  'item',
  'its',
  'itself',
  'job',
  'join',
  'just',
  'keep',
  'key',
  'kid',
  'kill',
  'kind',
  'kitchen',
  'know',
  'knowledge',
  'land',
  'language',
  'large',
  'last',
  'late',
  'later',
  'laugh',
  'law',
  'lawyer',
  'lay',
  'lead',
  'leader',
  'learn',
  'least',
  'leave',
  'left',
  'leg',
  'legal',
  'less',
  'let',
  'letter',
  'level',
  'lie',
  'life',
  'light',
  'like',
  'likely',
  'line',
  'list',
  'listen',
  'little',
  'live',
  'local',
  'long',
  'look',
  'lose',
  'loss',
  'lot',
  'love',
  'low',
  'machine',
  'magazine',
  'main',
  'maintain',
  'major',
  'majority',
  'make',
  'man',
  'manage',
  'management',
  'manager',
  'many',
  'market',
  'marriage',
  'material',
  'matter',
  'may',
  'maybe',
  'me',
  'mean',
  'measure',
  'media',
  'medical',
  'meet',
  'meeting',
  'member',
  'memory',
  'mention',
  'message',
  'method',
  'middle',
  'might',
  'military',
  'million',
  'mind',
  'minute',
  'miss',
  'mission',
  'model',
  'modern',
  'moment',
  'money',
  'month',
  'more',
  'morning',
  'most',
  'mother',
  'mouth',
  'move',
  'movement',
  'movie',
  'much',
  'music',
  'must',
  'my',
  'myself',
  'name',
  'nation',
  'national',
  'natural',
  'nature',
  'near',
  'nearly',
  'necessary',
  'need',
  'network',
  'never',
  'new',
  'news',
  'newspaper',
  'next',
  'nice',
  'night',
  'no',
  'none',
  'nor',
  'north',
  'not',
  'note',
  'nothing',
  'notice',
  'now',
  'number',
  'occur',
  'of',
  'off',
  'offer',
  'office',
  'officer',
  'official',
  'often',
  'oh',
  'oil',
  'ok',
  'old',
  'on',
  'once',
  'one',
  'only',
  'onto',
  'open',
  'operation',
  'opportunity',
  'option',
  'or',
  'order',
  'organization',
  'other',
  'others',
  'our',
  'out',
  'outside',
  'over',
  'own',
  'owner',
  'page',
  'pain',
  'painting',
  'paper',
  'parent',
  'part',
  'participant',
  'particular',
  'particularly',
  'partner',
  'party',
  'pass',
  'past',
  'patient',
  'pattern',
  'pay',
  'peace',
  'people',
  'per',
  'perform',
  'performance',
  'perhaps',
  'period',
  'person',
  'personal',
  'phone',
  'physical',
  'pick',
  'picture',
  'piece',
  'place',
  'plan',
  'plant',
  'play',
  'player',
  'point',
  'police',
  'policy',
  'political',
  'politics',
  'poor',
  'popular',
  'population',
  'position',
  'positive',
  'possible',
  'power',
  'practice',
  'prepare',
  'present',
  'president',
  'pressure',
  'pretty',
  'prevent',
  'price',
  'private',
  'probably',
  'problem',
  'process',
  'produce',
  'product',
  'production',
  'professional',
  'professor',
  'program',
  'project',
  'property',
  'protect',
  'prove',
  'provide',
  'public',
  'pull',
  'purpose',
  'push',
  'put',
  'quality',
  'question',
  'quickly',
  'quite',
  'race',
  'radio',
  'raise',
  'range',
  'rate',
  'rather',
  'reach',
  'read',
  'ready',
  'real',
  'reality',
  'realize',
  'really',
  'reason',
  'receive',
  'recent',
  'recently',
  'recognize',
  'record',
  'red',
  'reduce',
  'reflect',
  'region',
  'relate',
  'relationship',
  'religious',
  'remain',
  'remember',
  'remove',
  'report',
  'represent',
  'require',
  'research',
  'resource',
  'respond',
  'response',
  'responsibility',
  'rest',
  'result',
  'return',
  'reveal',
  'rich',
  'right',
  'rise',
  'risk',
  'road',
  'rock',
  'role',
  'room',
  'rule',
  'run',
  'safe',
  'same',
  'save',
  'say',
  'scene',
  'school',
  'science',
  'scientist',
  'score',
  'sea',
  'season',
  'seat',
  'second',
  'section',
  'security',
  'see',
  'seek',
  'seem',
  'sell',
  'send',
  'senior',
  'sense',
  'series',
  'serious',
  'serve',
  'service',
  'set',
  'seven',
  'several',
  'shake',
  'share',
  'she',
  'shoot',
  'short',
  'shot',
  'should',
  'shoulder',
  'show',
  'side',
  'sign',
  'significant',
  'similar',
  'simple',
  'simply',
  'since',
  'sing',
  'single',
  'sister',
  'sit',
  'site',
  'situation',
  'six',
  'size',
  'skill',
  'skin',
  'small',
  'smile',
  'so',
  'social',
  'society',
  'soldier',
  'some',
  'somebody',
  'someone',
  'something',
  'sometimes',
  'son',
  'song',
  'soon',
  'sort',
  'sound',
  'source',
  'south',
  'southern',
  'space',
  'speak',
  'special',
  'specific',
  'speech',
  'spend',
  'sport',
  'spring',
  'staff',
  'stage',
  'stand',
  'standard',
  'star',
  'start',
  'state',
  'statement',
  'station',
  'stay',
  'step',
  'still',
  'stock',
  'stop',
  'store',
  'story',
  'strategy',
  'street',
  'strong',
  'structure',
  'student',
  'study',
  'stuff',
  'style',
  'subject',
  'success',
  'successful',
  'such',
  'suddenly',
  'suffer',
  'suggest',
  'summer',
  'support',
  'sure',
  'surface',
  'system',
  'table',
  'take',
  'talk',
  'task',
  'tax',
  'teach',
  'teacher',
  'team',
  'technology',
  'television',
  'tell',
  'ten',
  'tend',
  'term',
  'test',
  'than',
  'thank',
  'that',
  'the',
  'their',
  'them',
  'themselves',
  'then',
  'theory',
  'there',
  'these',
  'they',
  'thing',
  'think',
  'third',
  'this',
  'those',
  'though',
  'thought',
  'thousand',
  'threat',
  'three',
  'through',
  'throughout',
  'throw',
  'thus',
  'time',
  'to',
  'today',
  'together',
  'tonight',
  'too',
  'top',
  'total',
  'tough',
  'toward',
  'town',
  'trade',
  'traditional',
  'training',
  'travel',
  'treat',
  'treatment',
  'tree',
  'trial',
  'trip',
  'trouble',
  'true',
  'truth',
  'try',
  'turn',
  'two',
  'type',
  'under',
  'understand',
  'unit',
  'until',
  'up',
  'upon',
  'us',
  'use',
  'usually',
  'value',
  'various',
  'very',
  'victim',
  'view',
  'violence',
  'visit',
  'voice',
  'vote',
  'wait',
  'walk',
  'wall',
  'want',
  'war',
  'watch',
  'water',
  'way',
  'we',
  'weapon',
  'wear',
  'week',
  'weight',
  'well',
  'west',
  'western',
  'what',
  'whatever',
  'when',
  'where',
  'whether',
  'which',
  'while',
  'white',
  'who',
  'whole',
  'whom',
  'whose',
  'why',
  'wide',
  'wife',
  'will',
  'win',
  'wind',
  'window',
  'wish',
  'with',
  'within',
  'without',
  'woman',
  'wonder',
  'word',
  'work',
  'worker',
  'world',
  'worry',
  'would',
  'write',
  'writer',
  'wrong',
  'yard',
  'yeah',
  'year',
  'yes',
  'yet',
  'you',
  'young',
  'your',
  'yourself',
];

export const htmlElementsList = [
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'code',
  'col',
  'data',
  'dd',
  'del',
  'details',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'label',
  'legend',
  'li',
  'link',
  'main',
  'map',
  'mark',
  'meta',
  'nav',
  'noscript',
  'object',
  'ol',
  'option',
  'p',
  'picture',
  'pre',
  'q',
  'script',
  'section',
  'select',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'sub',
  'sup',
  'svg',
  'table',
  'tbody',
  'td',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'tr',
  'ul',
  'video',
];

export const javascriptWordList = [
  'console',
  '.log',
  'Object',
  'object',
  '.keys',
  '.push',
  '.shift',
  '.unshift',
  '.pop',
  'NaN',
  'Math',
  'Infinity',
  '.isArray',
  'array',
  'async',
  'await',
  'const',
  'let',
  'var',
  '=',
  '[]',
  '{}',
  'return',
  'function',
  '=>',
  'break',
  'continue',
  'while',
  'for',
  'continue',
  'try',
  'catch',
  'debugger',
  'throw',
  'of',
  'import',
  'from',
  'true',
  'false',
  '===',
  '!==',
  'module',
  '.addEventListener',
  'document',
  '.querySelector',
  '.getElementById',
  '``',
];
////////////////////////////////////////////////////////////////////////////////////
